### ISSUE TITLE
Review Base_getattro implementation for Python 3.7 compatibility

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/ExtensionClass#13]
Python 3.7 is introducing a number of new OP codes to speed up method calling. I don't understand all the details, but `object.c` has a new `_PyObject_GetMethod` method, which is doing almost the same as `_PyObject_GenericGetAttrWithDict`, which is the basis for our customized `Base_getattro`.

The implementation on the Python side is spread out over a couple of issues, the two most relevant I could find are http://bugs.python.org/issue26110 and http://bugs.python.org/issue29263, with the initial patch adding the new method in https://hg.python.org/cpython/rev/64afd5cab40a.

Before we can support Python 3.7, someone should have a detailed look at this. Hopefully if we do nothing everything continues to work. But there might be an opportunity to opt-into the new feature and benefit from the new op code optimizations for classes deriving from ExtensionClass.

**Comment by stephan-hof** [comment]
Wow, very nice catch !

I think by doing nothing we are save because of this line: https://hg.python.org/cpython/file/tip/Objects/object.c#l1051
It detects our overwritten `tp_getattro` and calls it.
Then `_PyObject_GetMethod` returns 0 to signal that something arbitrary came back, so the normal/slow path is taken.

It could be that we can utilize these new OP codes, but right now I don't see a obvious way how :disappointed:

**Comment by hannosch** [comment]
Ok, thanks for confirming this. Python 3.7 is still under very active development, so their implementation might change. I'll leave this issue open as a reminder.

**Comment by jamadden** [comment]
I think PR #20 at least partially addresses this by showing that all the tests pass under 3.7.
