### ISSUE TITLE
Py_TPFLAGS_HAVE_CLASS in ExtensionClass.h

### ISSUE THREAD

**Issue by hannosch** [zopefoundation/ExtensionClass#14]
The ``PyMem_DEL`` macro in ExtensionClass.h uses `Py_TPFLAGS_HAVE_CLASS` unconditionally on both Python 2 and 3, though it's always true and gone in Python 3. Our `_compat.h` file has a helper macro `HAS_TP_DESCR_GET` for the same check, which should probably be used:

```
#define PyMem_DEL(O)                                   \
  if ((Py_TYPE(O)->tp_flags & Py_TPFLAGS_HAVE_CLASS) \
      && (Py_TYPE(O)->tp_free != NULL))              \
    Py_TYPE(O)->tp_free((PyObject*)(O));             \
  else                                                 \
    PyObject_FREE((O));
```

I'm just not sure if `ExtensionClass.h` should include `_compat.h` now or if there's some problem with that. Or if maybe more of this macro could be avoided under Python 3.

**Comment by davisagli** [comment]
I don't know the answers, but anecdotally, I was just able to get AccessControl to build by changing its copy of ExtensionClass.h to use HAS_TP_DESCR_GET here, even without including _compat.h anywhere new.

**Comment by stephan-hof** [comment]
From my point of view this whole macro is **very** dangerous and the best would be to get rid of it.
`PyMem_DEL` is meant to delete an arbitrary chunk of data. See here https://docs.python.org/3.5/c-api/memory.html?highlight=pymem_del#c.PyMem_Del

With this redefinition we change the meaning to: "Free an object". So if people use `PyMem_Del` as documented in the python docu they are risking segfaults. 

Mapping `PyObject_DEL` to `PyMem_DEL` is also dangerous, because different allocators are used behind the scenes.
According to this https://docs.python.org/2/whatsnew/2.5.html `PyObject_XX` and `PyMEM_XX` cannot be mixed anymore.
`With 2.5’s changes to obmalloc, these families now do different things and mismatches will probably result in a segfault. You should carefully test your C extension modules with Python 2.5`

I searched where `PyMem_Del` is used inside zopefoundation code.
https://github.com/search?q=org%3Azopefoundation+PyMem_DEL&type=Code
The only occurrence is in `ExtensionClass.h` copied to the various repos using ExtensionClass.
The same is true for `PyObject_FREE`.

I guess back at the days, when new style classes were introduced, there was a use for this macro.
Hence the comment, but nowadays they have no use.

So if nobody objects I'll prepare a pull request to get rid of this macros.

**Comment by hannosch** [comment]
+1 for removing the macro
